### ISSUE TITLE
tslib is a dependency, but is not listed in package.json

### ISSUE THREAD

**Issue by jdell64** [cartant/rxjs-tslint-rules#18]
I was working on an angular project using `@angular/animations` which has a dependency on `tslib: ^1.7.1` which produces the following error when running the linter rules:

```
tslib_1.__makeTemplateObject is not a function
TypeError: tslib_1.__makeTemplateObject is not a function
    at /myproject/node_modules/rxjs-tslint-rules/dist/rules/rxjsAddRule.js:27:95
    at Object.<anonymous> (/myproject/node_modules/rxjs-tslint-rules/dist/rules/rxjsAddRule.js:35:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at loadRule (/myproject/node_modules/tslint/lib/ruleLoader.js:96:26)
```

This was resolved by removing `node_modules/tslib` and rerunning npm install which pulled down tslib 1.8.0 as a dependency of `@angular/animations`.

`package.json` for `rxjs-tslint-rules` doesn't list tslib as a dependency but it looks like it is. It should probably be added with the minimum version of `1.8.0`.

**Comment by cartant** [comment]
Thanks. Fixed in 3.1.1.
