### ISSUE TITLE
TypeError: Cannot read property 'kind' of undefined in rxjsFinnishRule

### ISSUE THREAD

**Issue by reppners** [cartant/rxjs-tslint-rules#34]
Hey there, added the rules to a project using 

TypeScript@2.6.2
TSLint@5.9.1

produced this stacktrace a couple of times:

```
TypeError: Cannot read property 'kind' of undefined
    at ./my-project/node_modules/rxjs-tslint-rules/dist/rules/rxjsFinnishRule.js:56:30
    at Array.forEach (native)
    at Walker.visitObjectLiteralExpression (./my-project/node_modules/rxjs-tslint-rules/dist/rules/rxjsFinnishRule.js:55:25)
    at Walker.SyntaxWalker.visitNode (./my-project/node_modules/tslint/lib/language/walker/syntaxWalker.js:449:22)
    at ./my-project/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNodes (./my-project/node_modules/typescript/lib/typescript.js:12699:30)
    at Object.forEachChild (./my-project/node_modules/typescript/lib/typescript.js:12830:21)
    at Walker.SyntaxWalker.walkChildren (./my-project/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:12)
    at Walker.SyntaxWalker.visitCallExpression (./my-project/node_modules/tslint/lib/language/walker/syntaxWalker.js:54:14)
    at Walker.SyntaxWalker.visitNode (./my-project/node_modules/tslint/lib/language/walker/syntaxWalker.js:305:22)
```

The process does not crash and completes showing lint failures concerning some files in the project as if nothing had gone wrong. I tried to get some info on the root nodes but a few console.logs haven't yielded anything that would have helped to track down the source.

**Comment by cartant** [comment]
Before I look any further, I have to ask: do you use the `no-unused-variable` rule or rely upon rule extensions that enable it be default? See issue #4 in this repo for an explanation.

**Comment by reppners** [comment]
No, don't use any `no-unused-var` since the TypeScript does the job with `noUnusedLocals` and `noUnusedParameters` in that codebase.

I've checked the stack traces again and they're not equal as I thought first. Here is the complete list of errors produced:

```
TypeError: Cannot read property 'kind' of undefined
    at ./my-project/node_modules/rxjs-tslint-rules/dist/rules/rxjsFinnishRule.js:56:30
    at Array.forEach (native)
    at Walker.visitObjectLiteralExpression (./my-project/node_modules/rxjs-tslint-rules/dist/rules/rxjsFinnishRule.js:55:25)
    at Walker.SyntaxWalker.visitNode (./my-project/node_modules/tslint/lib/language/walker/syntaxWalker.js:449:22)
    at ./my-project/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNodes (./my-project/node_modules/typescript/lib/typescript.js:12699:30)
    at Object.forEachChild (./my-project/node_modules/typescript/lib/typescript.js:12830:21)
    at Walker.SyntaxWalker.walkChildren (./my-project/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:12)
    at Walker.SyntaxWalker.visitCallExpression (./my-project/node_modules/tslint/lib/language/walker/syntaxWalker.js:54:14)
    at Walker.SyntaxWalker.visitNode (./my-project/node_modules/tslint/lib/language/walker/syntaxWalker.js:305:22)
```
```
TypeError: Cannot read property 'kind' of undefined
    at ./my-project/node_modules/rxjs-tslint-rules/dist/rules/rxjsFinnishRule.js:56:30
    at Array.forEach (native)
    at Walker.visitObjectLiteralExpression (./my-project/node_modules/rxjs-tslint-rules/dist/rules/rxjsFinnishRule.js:55:25)
    at Walker.SyntaxWalker.visitNode (./my-project/node_modules/tslint/lib/language/walker/syntaxWalker.js:449:22)
    at ./my-project/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNode (./my-project/node_modules/typescript/lib/typescript.js:12690:24)
    at Object.forEachChild (./my-project/node_modules/typescript/lib/typescript.js:12754:21)
    at Walker.SyntaxWalker.walkChildren (./my-project/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:12)
    at Walker.SyntaxWalker.visitVariableDeclaration (./my-project/node_modules/tslint/lib/language/walker/syntaxWalker.js:261:14)
    at Walker.SyntaxWalker.visitNode (./my-project/node_modules/tslint/lib/language/walker/syntaxWalker.js:515:22)
```
```
TypeError: Cannot read property 'kind' of undefined
    at ./my-project/node_modules/rxjs-tslint-rules/dist/rules/rxjsFinnishRule.js:56:30
    at Array.forEach (native)
    at Walker.visitObjectLiteralExpression (./my-project/node_modules/rxjs-tslint-rules/dist/rules/rxjsFinnishRule.js:55:25)
    at Walker.SyntaxWalker.visitNode (./my-project/node_modules/tslint/lib/language/walker/syntaxWalker.js:449:22)
    at ./my-project/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNode (./my-project/node_modules/typescript/lib/typescript.js:12690:24)
    at Object.forEachChild (./my-project/node_modules/typescript/lib/typescript.js:12857:21)
    at Walker.SyntaxWalker.walkChildren (./my-project/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:12)
    at Walker.SyntaxWalker.visitBinaryExpression (./my-project/node_modules/tslint/lib/language/walker/syntaxWalker.js:39:14)
    at Walker.SyntaxWalker.visitNode (./my-project/node_modules/tslint/lib/language/walker/syntaxWalker.js:293:22)
```
```
TypeError: Cannot read property 'kind' of undefined
    at ./my-project/node_modules/rxjs-tslint-rules/dist/rules/rxjsFinnishRule.js:56:30
    at Array.forEach (native)
    at Walker.visitObjectLiteralExpression (./my-project/node_modules/rxjs-tslint-rules/dist/rules/rxjsFinnishRule.js:55:25)
    at Walker.SyntaxWalker.visitNode (./my-project/node_modules/tslint/lib/language/walker/syntaxWalker.js:449:22)
    at ./my-project/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNode (./my-project/node_modules/typescript/lib/typescript.js:12690:24)
    at Object.forEachChild (./my-project/node_modules/typescript/lib/typescript.js:12915:24)
    at Walker.SyntaxWalker.walkChildren (./my-project/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:12)
    at Walker.SyntaxWalker.visitReturnStatement (./my-project/node_modules/tslint/lib/language/walker/syntaxWalker.js:222:14)
    at Walker.SyntaxWalker.visitNode (./my-project/node_modules/tslint/lib/language/walker/syntaxWalker.js:476:22)
```
```
TypeError: Cannot read property 'kind' of undefined
    at ./my-project/node_modules/rxjs-tslint-rules/dist/rules/rxjsFinnishRule.js:56:30
    at Array.forEach (native)
    at Walker.visitObjectLiteralExpression (./my-project/node_modules/rxjs-tslint-rules/dist/rules/rxjsFinnishRule.js:55:25)
    at Walker.SyntaxWalker.visitNode (./my-project/node_modules/tslint/lib/language/walker/syntaxWalker.js:449:22)
    at ./my-project/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:63
    at visitNode (./my-project/node_modules/typescript/lib/typescript.js:12690:24)
    at Object.forEachChild (./my-project/node_modules/typescript/lib/typescript.js:12754:21)
    at Walker.SyntaxWalker.walkChildren (./my-project/node_modules/tslint/lib/language/walker/syntaxWalker.js:535:12)
    at Walker.SyntaxWalker.visitPropertyAssignment (./my-project/node_modules/tslint/lib/language/walker/syntaxWalker.js:210:14)
    at Walker.SyntaxWalker.visitNode (./my-project/node_modules/tslint/lib/language/walker/syntaxWalker.js:464:22)
```

I can put a console.log into the rule where the TypeError occurs but I don't know what to log to track down the location in the source file.

**Comment by cartant** [comment]
Thanks. It's a little strange. It appears to be failing on this line:

```js
if (property.name.kind !== ts.SyntaxKind.ComputedPropertyName) {
```
Where `property` is an object literal property. It's easy enough to fix, but I'd have thought that all object literal properties would have to have a `name`. I'm curious as to whether there's some syntax I've not thought of.

I can fix this, but if you can narrow it down to the source that effects the error, I'd be grateful.

**Comment by reppners** [comment]
Printed the nodes that caused the failures and was able to track it down to object spread statements.

e.g.
```
const info = {
    quality: "default",
    qualityIcon: "default"
};

const specificInfo = {
    ...info,
    quality: "good",
    qualityIcon: "thumbs-up"
};
```

**Comment by cartant** [comment]
Thanks.

After thinking about it a little, after I posted the previous comment, it did occur to me that the object spread syntax might have been the culprit. However, I've just added the syntax the fixtures and they still pass - which is a little annoying. I'd have like to see a failure. Will keep messing with it and will fix it soon.

**Comment by cartant** [comment]
Yep. Reproduced it in the fixtures. Thanks.

**Comment by cartant** [comment]
Should be fixed in 3.7.2.

**Comment by reppners** [comment]
It does! Thanks for the sonic speed bug fixing 😃

**Comment by cartant** [comment]
No worries. Bug reports like this one make for easy fixes, so thanks.
