### ISSUE TITLE
TypeError: Cannot read property 'getDeclarations' of undefined

### ISSUE THREAD

**Issue by tenyps** [cartant/rxjs-tslint-rules#42]
"rxjs-no-unsafe-scope": {
      "severity": "error"
    }

TypeError: Cannot read property 'getDeclarations' of undefined
    at Walker.isUnsafe (C:\T\node_modules\rxjs-tslint-rules\dist\rules\rxjsNoUnsafeScopeRule.js:96:34)
    at Walker.visitNode (C:\T\node_modules\rxjs-tslint-rules\dist\rules\rxjsNoUnsafeScopeRule.js:81:38)
    at C:\T\node_modules\tslint\lib\language\walker\syntaxWalker.js:535:63
    at visitNode (C:\T\node_modules\typescript\lib\typescript.js:12690:24)
    at Object.forEachChild (C:\T\node_modules\typescript\lib\typescript.js:12822:21)
    at Walker.SyntaxWalker.walkChildren (C:\T\node_modules\tslint\lib\language\walker\syntaxWalker.js:535:12)
    at Walker.SyntaxWalker.visitPropertyAccessExpression (C:\T\node_modules\tslint\lib\language\walker\syntaxWalker.js:207:14)
    at Walker.SyntaxWalker.visitNode (C:\T\node_modules\tslint\lib\language\walker\syntaxWalker.js:461:22)
    at Walker.visitNode (C:\T\node_modules\rxjs-tslint-rules\dist\rules\rxjsNoUnsafeScopeRule.js:85:36)
    at C:\T\node_modules\tslint\lib\language\walker\syntaxWalker.js:535:63

**Comment by tenyps** [comment]
Node
-------------------------------
IdentifierObject {
  pos: 3864,
  end: 3876,
  flags: 0,
  parent: 
   NodeObject {
     pos: 3862,
     end: 3876,
     flags: 0,
     transformFlags: 536870912,
     parent: 
      NodeObject {
        pos: 3850,
        end: 3877,
        flags: 0,
        transformFlags: 536870912,
        parent: [Object],
        kind: 181,
        expression: [Object],
        arguments: [Array] },
     kind: 179,
     expression: 
      IdentifierObject {
        pos: 3862,
        end: 3863,
        flags: 0,
        parent: [Circular],
        escapedText: 'd',
        flowNode: [Object],
        transformFlags: 536870912,
        id: 1085 },
     name: [Circular],
     flowNode: { flags: 2, container: [Object] },
     id: 1107 },
  escapedText: 'StartDate',
  flowNode: 
   { flags: 2,
     container: 
      NodeObject {
        pos: 3821,
        end: 3913,
        flags: 0,
        transformFlags: 570425344,
        parent: [Object],
        kind: 186,
        modifiers: undefined,
        asteriskToken: undefined,
        modifierFlagsCache: 536870912,
        name: undefined,
        typeParameters: undefined,
        parameters: [Array],
        type: undefined,
        body: [Object],
        flowNode: [Object],
        symbol: [Object],
        locals: [Object],
        nextContainer: [Object],
        id: 796 } },
  transformFlags: 536870912 }
-----------------------------------------------
Symbol 

undefined

**Comment by cartant** [comment]
Closing this, as nothing can be done without additional information.
