### ISSUE TITLE
TypeError: Cannot read property 'resolvedReturnType' of undefined

### ISSUE THREAD

**Issue by tenyps** [cartant/rxjs-tslint-rules#43]
v. 3.16.1

Rule:
```
"rxjs-throw-error": {
      "severity": "error"
 }
```
Error:

```
	TypeError: Cannot read property 'resolvedReturnType' of undefined
    at Object.getReturnTypeOfSignature (C:\T\node_modules\typescript\lib\typescript.js:29729:28)
    at Walker.visitCallExpression (C:\T\node_modules\rxjs-tslint-rules\dist\rules\rxjsThrowErrorRule.js:50:42)
    at Walker.SyntaxWalker.visitNode (C:\T\node_modules\tslint\lib\language\walker\syntaxWalker.js:305:22)
    at C:\T\node_modules\tslint\lib\language\walker\syntaxWalker.js:535:63
    at visitNode (C:\T\node_modules\typescript\lib\typescript.js:12690:24)
    at Object.forEachChild (C:\T\node_modules\typescript\lib\typescript.js:12857:21)
    at Walker.SyntaxWalker.walkChildren (C:\T\node_modules\tslint\lib\language\walker\syntaxWalker.js:535:12)
    at Walker.SyntaxWalker.visitBinaryExpression (C:\T\node_modules\tslint\lib\language\walker\syntaxWalker.js:39:14)
    at Walker.SyntaxWalker.visitNode (C:\T\node_modules\tslint\lib\language\walker\syntaxWalker.js:293:22)
    at C:\T\node_modules\tslint\lib\language\walker\syntaxWalker.js:535:63
```

**Comment by cartant** [comment]
Closing this, as nothing can be done without additional information.
