### ISSUE TITLE
TypeError: nodes.push is not a function

### ISSUE THREAD

**Issue by RazorSK** [cartant/rxjs-tslint-rules#6]
I've encountered error that I am not able to reproduce in any shareable way.

```
TypeError: nodes.push is not a function
    at Function.AddedWalker.add (C:\k\artemis\node_modules\rxjs-tslint-rules\dist\support\added-walker.js:19:15)
    at C:\k\artemis\node_modules\rxjs-tslint-rules\dist\support\used-walker.js:26:36
    at visitNode (C:\Users\bodingm\AppData\Roaming\npm\node_modules\typescript\lib\typescript.js:15944:20)
    at Object.forEachChild (C:\Users\bodingm\AppData\Roaming\npm\node_modules\typescript\lib\typescript.js:16087:24)
    at NodeObject.forEachChild (C:\Users\bodingm\AppData\Roaming\npm\node_modules\typescript\lib\typescript.js:88427:23)
    at Walker.UsedWalker.visitCallExpression (C:\k\artemis\node_modules\rxjs-tslint-rules\dist\support\used-walker.js:18:14)
    at Walker.SyntaxWalker.visitNode (C:\k\artemis\node_modules\tslint\lib\language\walker\syntaxWalker.js:305:22)
    at Walker.AddedWalker.visitNode (C:\k\artemis\node_modules\rxjs-tslint-rules\dist\support\added-walker.js:37:36)
    at C:\k\artemis\node_modules\tslint\lib\language\walker\syntaxWalker.js:535:63
    at visitNode (C:\k\artemis\node_modules\typescript\lib\typescript.js:15944:20)
```
Checking for existence of nodes.push worked well.
```
        if (nodes === undefined || !nodes.push) {
            map[key] = nodes = [];
        }
```

**Comment by cartant** [comment]
For that error to have occurred, the map in question would have to have a non-array in it. At the moment, I cannot see how that could occur, as all additions to the used and added maps appear to be performed using the static `add` method - from which the error is thrown.

Ideally, this should be reproduce-able. As it is, I have no idea how you are using it. At the very least, you'd need to include your configuration details, but without a repro, I don't see a way forward.

**Comment by RazorSK** [comment]
Error occurred again and I was able to debug and find cause of this problem.

Problem is caused by using Angular's
`this.route.url.toString()`
`this.route` is ActivatedRoute object
`this.route.url` is Observable

so in 
`AddedWalker.add = function (map, key, node)`
map is 
`map: Object {takeUntil: Array(2), map: Array(1), filter: Array(2)}`
and key is
`key: "toString"`

In
```
var nodes = map[key];
if (nodes === undefined) {
```
we check `nodes` for undefined, but `toString `already exist in `map.__proto__` so we have `map.__proto__.toString` in `nodes`.

**Comment by cartant** [comment]
Very nicely spotted. Thanks.
