### ISSUE TITLE
rxjs-no-unsafe-catch throws error when matching

### ISSUE THREAD

**Issue by Kunepro** [cartant/rxjs-tslint-rules#96]
When the rule `rxjs-no-unsafe-catch` matches an error is thrown:
```
The 'rxjs-no-unsafe-catch' rule threw an error in 'C:/Users/<edited>/apps/appointment-editor/src/app/store/appointments/appointments.effects.ts':
TypeError: Cannot read property 'kind' of undefined
    at Object.isFunctionDeclaration (C:\Users\<edited>\node_modules\tsutils\typeguard\2.8\node.js:294:17)
    at isUnsafe (C:\Users\<edited>\node_modules\rxjs-tslint-rules\dist\rules\rxjsNoUnsafeCatchRule.js:147:17)
    at C:\Users\<edited>\node_modules\rxjs-tslint-rules\dist\rules\rxjsNoUnsafeCatchRule.js:120:21
    at Array.forEach (<anonymous>)
    at Walker.walkPipedOperators (C:\Users\<edited>\node_modules\rxjs-tslint-rules\dist\rules\rxjsNoUnsafeCatchRule.js:117:24)
    at C:\Users\<edited>\node_modules\rxjs-tslint-rules\dist\rules\rxjsNoUnsafeCatchRule.js:135:27
    at Array.forEach (<anonymous>)
    at Walker.walkPipedTypes (C:\Users\<edited>\node_modules\rxjs-tslint-rules\dist\rules\rxjsNoUnsafeCatchRule.js:130:24)
    at Walker.visitCallExpression (C:\Users\<edited>\node_modules\rxjs-tslint-rules\dist\rules\rxjsNoUnsafeCatchRule.js:75:34)
    at Walker.SyntaxWalker.visitNode (C:\Users\<edited>\node_modules\tslint\lib\language\walker\syntaxWalker.js:305:22)
    at C:\Users\<edited>\node_modules\tslint\lib\language\walker\syntaxWalker.js:535:63
    at visitNode (C:\Users\<edited>\node_modules\typescript\lib\typescript.js:16135:24)
    at Object.forEachChild (C:\Users\<edited>\node_modules\typescript\lib\typescript.js:16209:21)
    at Walker.SyntaxWalker.walkChildren (C:\Users\<edited>\node_modules\tslint\lib\language\walker\syntaxWalker.js:535:12)
    at Walker.SyntaxWalker.visitPropertyDeclaration (C:\Users\<edited>\node_modules\tslint\lib\language\walker\syntaxWalker.js:213:14)
    at Walker.SyntaxWalker.visitNode (C:\Users\<edited>\node_modules\tslint\lib\language\walker\syntaxWalker.js:467:22)
```
Code that matched:
```
	@Effect()
	initialiseAppointments$ = this.actions$.pipe(
		ofType(AppointmentsActions.Type.Initialise),
		this.getAppointmentSessionParametersFromURL(),
		this.updateAppointmentSessionIfDeprecated(),
		map((appointmentSession: AppointmentSession) => new AppointmentsActions.InitialiseSuccess(appointmentSession)),
		catchError(() => of(new AppointmentsActions.InitialiseError())),
	);
```
TSLint rule:
`"rxjs-no-unsafe-catch":          true,`
The effect is wrong and needs to be changed, however I would expect the lint to report the error but not to actually throw one.

**Comment by cartant** [comment]
This should be fixed in 4.23.2.
